#! /usr/bin/env python3

import struct
import os
import sys
import mmap
import numpy as np
from functools import lru_cache
from multiprocessing import Pool
from tqdm import tqdm

# 32 Bits module
global mod, mod1, f
mod = 2 ** 32
mod1 = 2 ** 31

# Generate Key array (EXTRA2: k0*4892+42816, <<7, +156, &0xCE, >>3)
# Cached: same k always yields the same key bytes
@lru_cache(maxsize=256)
def gk(k: int):
    a = (k * 4892 + 42816) % mod
    b = (a << 7 ^ a) % mod
    out = []
    for _ in range(256):
        a = (a - k + b) % mod
        b = (a + 156) % mod
        a = (a * (b & 0xCE)) % mod
        out.append(a & 255)
        a = a >> 3
    return out

# decrypt data with key(Generated by k)
# EXTRA2: XOR period 179, final XOR 0x77; in-place uint8 ops avoid extra allocations
def dd(data: bytes, k: int):
    key = np.array(gk(k), dtype='uint8')
    d = np.frombuffer(data, dtype='uint8').copy()
    datalen = len(d)
    d ^= np.resize(key[:179], datalen)
    d += 3
    d += np.resize(key[:89], datalen)
    d ^= 0x77
    return d.tobytes()


# Parse file header and get file list & location for decrypt
# EXTRA2: num = sum of header ints at indices 3..254 (252 values, header[12:-4])
def getInfo():
    f.seek(0)
    header = f.read(1024)
    num = 0
    num = (sum(struct.unpack(252 * "i", header[12:-4])) + mod1) % mod - mod1
    raw = dd(f.read(16 * num), struct.unpack("I", header[212:216])[0])
    start = struct.unpack("I", raw[12:16])[0]
    array = dd(f.read(start - 1024 - 16 * num), struct.unpack("I", header[92:96])[0])
    out = []
    for i in range(num):
        l, offset, k, p = struct.unpack("IIII", raw[16 * i:16 * (i + 1)])
        name = array[offset:array.find(0, offset)].decode("ascii")
        out.append((name, p, l, k))
    return out

# Per-process mmap; initialized lazily on first extract() call in each worker
_mm = None

# Locate position, create file, then write decrypted binaries
def extract(files):
    global _mm
    if _mm is None:
        _mm = mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ)
    name, p, l, k = files
    os.makedirs(os.path.dirname(name), exist_ok=True)
    with open(name, "wb") as o:
        o.write(dd(_mm[p:p+l], k))
    return name

f = open(sys.argv[1], "rb")

# Entry: argv1-> .dat file path; argv2-> output path
if __name__ == "__main__":
    files = getInfo()
    if len(sys.argv) == 3:
        files = [(os.path.join(sys.argv[2], name), p, l, k) for name, p, l, k in files]
        with Pool(processes=os.cpu_count()) as pool:
            for _ in tqdm(pool.imap_unordered(extract, files, chunksize=4), total=len(files)):
                pass

    elif len(sys.argv) == 2:
        for item in files:
            print(item[0], item[2], "\tKByte(s)")

